export const ActionType = Object.freeze({
    QUARTER: "QUARTER",
    HOME_SETTING: "HOME_SETTING",
    AWAY_SETTING: "AWAY_SETTING",
    // GAME_CLOCK_SET: "GAME_CLOCK_SET",
    // SHOT_CLOCK_RESET: "SHOT_CLOCK_RESET",
    // HOME_SCORE_PLUS_1: "HOME_SCORE_PLUS_1",
    // AWAY_SCORE_PLUS_1: "AWAY_SCORE_PLUS_1",
});
