plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
    id "io.sentry.jvm.gradle" version "5.12.2"
}

group = 'com.nincore'
version = '0.0.1-SNAPSHOT'
description = 'nincoreboard-api'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    annotationProcessor 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework:spring-websocket'
    implementation "org.springframework.boot:spring-boot-starter-actuator"

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'com.h2database:h2'
    implementation 'io.sentry:sentry-spring-boot-starter-jakarta:7.10.0'

}

sentry {
    // Generates a JVM (Java, Kotlin, etc.) source bundle and uploads your source code to Sentry.
    // This enables source context, allowing you to see your source
    // code as part of your stack traces in Sentry.
    includeSourceContext = true

    org = "nincoreboard-api"
    projectName = "java-spring-boot"
    authToken = System.getenv("sntrys_eyJpYXQiOjE3Njk1ODIyMDAuMjg2MzY0LCJ1cmwiOiJodHRwczovL3NlbnRyeS5pbyIsInJlZ2lvbl91cmwiOiJodHRwczovL3VzLnNlbnRyeS5pbyIsIm9yZyI6Im5pbm5vbmcifQ")
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.named('sentryUploadSourceBundleJava') {
    enabled = false
}
