config:
  target: 'http://localhost:8080'
  phases:
    - duration: 10
      arrivalRate: 1
    - duration: 60
      arrivalRate: 5
scenarios:
  - flow:
      - post:
          url: "/api/login"
          headers:
            Content-Type: "application/json"
          json:
            ip: "test_{{ $randomNumber(1, 99999) }}"
            password: "load_test"

